<?php

namespace ContainerNa6kxiD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FxyxYaoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FxyxYao' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FxyxYao'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'author' => ['privates', '.errored..service_locator.FxyxYao.App\\Entity\\Author', NULL, 'Cannot autowire service ".service_locator.FxyxYao": it needs an instance of "App\\Entity\\Author" but this type has been excluded in "config/services.yaml".'],
            'serializer' => ['privates', 'serializer', 'getSerializerService', false],
        ], [
            'author' => 'App\\Entity\\Author',
            'serializer' => '?',
        ]);
    }
}
