<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerU6Hh0Og\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU6Hh0Og/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerU6Hh0Og.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerU6Hh0Og\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerU6Hh0Og\App_KernelDevDebugContainer([
    'container.build_hash' => 'U6Hh0Og',
    'container.build_id' => 'b2370b58',
    'container.build_time' => 1706733415,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerU6Hh0Og');
